title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: ""  # This remains empty unless you're hosting the site in a subdirectory
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true
  blogs:
    output: true

# Defaults configuration for multilingual content (optional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"

languages:
  - es
  - de
  - it

# Subdomain specific settings
subdomains:
  wsopfreechips:
    title: "WSOP Free Chips"
    description: "Daily bonuses and free chips for WSOP poker. Claim your rewards now!"
  hititrichfreecoins:
    title: "Hit It Rich Free Coins"
    description: "Daily free coins and rewards for Hit It Rich. Don't miss out on your bonuses!"