title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: "/games/wsopfreechips" # Make sure this points to the subdomain or subdirectory
url: "https://bonuscollector.net" # Main URL of your site

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Collections (if you have content specific to /games/wsopfreechips)
collections:
  pages:
    output: true
  blogs:
    output: true
  wsopfreechips:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

languages:
  - es
  - de
  - it