# General site settings
title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
url: "https://bonuscollector.net"  # Your main domain
baseurl: ""  # No baseurl for the main site

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Collections (optional)
collections:
  pages:
    output: true
  blogs:
    output: true

# Defaults for posts in different languages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

# Languages (optional for multi-language sites)
languages:
  - es
  - de
  - it

# Subdomain-specific configurations
# Settings for the wsopfreechips subdomain
wsopfreechips:
  url: "https://wsopfreechips.bonuscollector.net"
  baseurl: "/wsopfreechips"
  title: "WSOP Free Chips"
  description: "Get your daily free WSOP chips and other rewards."

# Settings for the hititrichfreecoins subdomain
hititrichfreecoins:
  url: "https://hititrichfreecoins.bonuscollector.net"
  baseurl: "/hititrichfreecoins"
  title: "Hit It Rich Free Coins"
  description: "Claim free coins for Hit It Rich slots and enjoy bonuses."