# Site-wide Settings for Root Domain
title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: "" # Root domain baseurl
url: "https://bonuscollector.net" # Root domain URL

markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Collections (Define collections if needed)
collections:
  pages:
    output: true
  blogs:
    output: true

# Defaults to control content scope
defaults:
  # Root Domain Defaults (Main site content)
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

  # Language-specific posts for Root Domain only
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"

  # WSOP Free Chips Subdomain
  - scope:
      path: "wsopfreechips"
    values:
      layout: "wsopfreechips"
      baseurl: "/wsopfreechips"
      url: "https://wsopfreechips.bonuscollector.net"

  # Hit It Rich Free Coins Subdomain
  - scope:
      path: "hititrichfreecoins"
    values:
      layout: "hititrichfreecoins"
      baseurl: "/hititrichfreecoins"
      url: "https://hititrichfreecoins.bonuscollector.net"

# Language Settings (Only for Root Domain)
languages:
  - es
  - de
  - it