# Site-wide Settings for Root Domain
title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: "" # Root domain baseurl
url: "https://bonuscollector.net" # Root domain URL

markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Collections (Optional: Define collections if needed)
collections:
  pages:
    output: true
  blogs:
    output: true

# Defaults to control content scope
defaults:
  # Root Domain Defaults (Main site content)
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

  # Language-specific posts for Root Domain only
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"

# Custom subdomain settings

# WSOP Free Chips Subdomain
wsopfreechips:
  title: "WSOP Free Chips - Daily Rewards"
  description: "Get the latest free chips and bonuses for WSOP on WSOPFreeChips."
  baseurl: "/wsopfreechips"
  url: "https://wsopfreechips.bonuscollector.net"
  path: "wsopfreechips"

# Hit It Rich Free Coins Subdomain
hititrichfreecoins:
  title: "Hit It Rich Free Coins - Daily Bonuses"
  description: "Daily free coins and bonuses for Hit It Rich on HitItRichFreeCoins."
  baseurl: "/hititrichfreecoins"
  url: "https://hititrichfreecoins.bonuscollector.net"
  path: "hititrichfreecoins"