title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true
  blogs:  # Add this collection for your blog posts
    output: true  # Ensure the blog posts are generated
    permalink: /:collection/:path/  # Customize permalink structure if needed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"
  - scope:
      path: "_blogs"  # Add this to set defaults for blog posts
      type: "blogs"
    values:
      layout: "post"
      lang: "en"  # You can adjust this or add more scopes for different languages
