title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

pagination:
  enabled: true
  per_page: 20
  permalink: "/page:num/"
  title: ":app_name - Page :num"
  sort_field: "date"
  sort_reverse: true

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"