title: "Bonus Collector: Free Coins, Chips, and Spins for Slot Games"
description: Get free coins, chips, spins, and various other rewards on our website. Enjoy exclusive bonuses and elevate your gaming experience with our daily updated offers and tips.
baseurl: "/bs-net"
url: "https://prollad99.github.io"

markdown: kramdown

paginate: 20
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"