title: Bonus Collector
description: Get free coins, chips, spins, and various other rewards on our website. Enjoy exclusive bonuses and elevate your gaming experience with our daily updated offers and tips.
baseurl: ""
url: "https://bonuscollector.net"

# Build settings
markdown: kramdown

paginate: 20
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:title/

collections:
  pages:
    output: true
