title: "Bonus Collector: Free Coins, Chips, and Spins for Slot Games"
description: Get free coins, chips, spins, and various other rewards on our website. Enjoy exclusive bonuses and elevate your gaming experience with our daily updated offers and tips.
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

paginate: 20
paginate_path: "/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at

permalink: /:title/

collections:
  pages:
    output: true

# Multilingual setup
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
