# _config.yml for Root Domain (bonuscollector.net)

title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: ""  # Leave baseurl empty for the root domain
url: "https://bonuscollector.net"  # Main URL for the root domain

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true
  blogs:
    output: true

# Set up defaults for language support (if required)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

# Additional language support (optional)
languages:
  - en
  - es
  - de
  - it

# Exclude subdomain content from the root domain
exclude:
  - "games/wsopfreechips/*"
