Title: "Bonus Collector: Free Coins, Spins & Rewards Daily"

baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true