Title: "Bonus Collector: Daily Free Coins, Spins & Slot Game Rewards"

Description: "Unlock daily free coins, chips, spins, and exclusive bonuses with Bonus Collector. Get the latest rewards and tips to boost your favorite slot games, all updated regularly to enhance your gameplay."

baseurl: ""
url: "https://www.bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"