title: "Bonus Collector: Free Slot Game Rewards"
description: "Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips."
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"

  # Tag pages in different languages
  - scope:
      path: "tag"
      type: "pages"
    values:
      layout: "tag"
      lang: "en"
  - scope:
      path: "es/tag"
      type: "pages"
    values:
      layout: "tag"
      lang: "es"
  - scope:
      path: "de/tag"
      type: "pages"
    values:
      layout: "tag"
      lang: "de"
  - scope:
      path: "it/tag"
      type: "pages"
    values:
      layout: "tag"
      lang: "it"