title: "Bonus Collector: Free Slot Game Rewards"
description: Get daily free coins, chips, spins, and exclusive bonuses for your favorite slot games. Elevate your gaming with our updated offers and tips.
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true

paginate: 20

pagination:
  enabled: true
  lang: [en, es, de, it]
  per_page: 20
  permalinks:
    en: "/page/:num/"
    es: "/es/page/:num/"
    de: "/de/page/:num/"
    it: "/it/page/:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"