title: "Bonus Collector: Free Slot Game Rewards"
description: Bonus Collector offers daily updates on free coins, chips, spins, and other rewards for popular slot games. Enhance your gaming experience with our exclusive bonuses and tips.
baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-last-modified-at

pagination:
  enabled: true
  per_page: 20
  permalink: "/page/:num/"
  title: ":title - Page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  lang: [en, es, de, it]
  category: "posts"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: "es"
      type: "posts"
    values:
      layout: "post"
      lang: "es"
  - scope:
      path: "de"
      type: "posts"
    values:
      layout: "post"
      lang: "de"
  - scope:
      path: "it"
      type: "posts"
    values:
      layout: "post"
      lang: "it"