title: "Bonus Collector"

url: "https://bonuscollector.net"
baseurl: ""

permalink: pretty
trailing_slash: true

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true