Title: "Bonus Collector: Free Coins, Spins & Rewards Daily"

Description: "Grab daily free coins, chips, spins & exclusive bonuses with Bonus Collector! Stay updated with rewards & tips to level up your favorite slot games!"

baseurl: ""
url: "https://bonuscollector.net"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

collections:
  pages:
    output: true