source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'
gem 'csv', '~> 3.1'
gem 'base64', '~> 0.1'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-last-modified-at'
gem 'jekyll-image-optim', '~> 1.0'
gem 'jekyll-webpack'