name: Delete gh-pages Branch

on:
  workflow_dispatch:

jobs:
  delete-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete gh-pages Branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
          git push origin --delete gh-pages