name: Deploy Jekyll site to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Create .vercelignore
        run: echo '_site/*' > .vercelignore

      - name: Check build size
        run: du -sh ./_site

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./_site
        continue-on-error: true

      - name: Retry if rate limit error
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "Waiting for 37 minutes due to rate limit..."
          sleep 2220
          echo "Retrying deployment..."
          npx vercel -t ${{ secrets.VERCEL_TOKEN }} -m githubCommitSha=$GITHUB_SHA -m githubCommitAuthorName=${{ github.actor }} -m githubCommitAuthorLogin=${{ github.actor }} -m githubDeployment=1 -m githubOrg=${{ github.repository_owner }} -m githubRepo=${{ github.event.repository.name }} -m githubCommitOrg=${{ github.repository_owner }} -m githubCommitRepo=${{ github.event.repository.name }} -m githubCommitMessage="${{ github.event.head_commit.message }}" -m githubCommitRef=${{ github.ref }}