name: Index URLs with Bing IndexNow

on:
  push:
    branches:
      - main
    paths:
      - _posts/**
      - sitemap.xml
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install requests xmltodict

    - name: Fetch and index new URLs with Bing IndexNow
      env:
        BING_API_KEY: ${{ secrets.BING_API_KEY }}
      run: |
        python <<EOF
        import requests
        import xmltodict

        # Configuration
        API_KEY = "${{ secrets.BING_API_KEY }}"
        SITEMAP_URL = "https://bonuscollector.net/sitemap.xml"

        # Fetch the sitemap
        response = requests.get(SITEMAP_URL)
        sitemap = xmltodict.parse(response.content)

        # Extract URLs from the sitemap
        urls = [url['loc'] for url in sitemap['urlset']['url']]

        # Read previously indexed URLs
        try:
            with open('indexed_urls.txt', 'r') as file:
                indexed_urls = file.read().splitlines()
        except FileNotFoundError:
            indexed_urls = []

        # Find new URLs to index
        new_urls = [url for url in urls if url not in indexed_urls]

        if not new_urls:
            print("No new URLs to index.")
            exit(0)

        # Notify Bing using IndexNow API
        INDEXNOW_ENDPOINT = "https://www.bing.com/indexnow"

        for url in new_urls:
            params = {
                "url": url,
                "key": API_KEY
            }
            response = requests.get(INDEXNOW_ENDPOINT, params=params)
            if response.status_code == 200:
                print(f"Indexed: {url}")
            else:
                print(f"Failed to index: {url}, Status Code: {response.status_code}")

        # Save new URLs to the indexed file
        with open('indexed_urls.txt', 'a') as file:
            for url in new_urls:
                file.write(url + '\n')
        EOF

    - name: Commit indexed URLs file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add indexed_urls.txt
        git commit -m 'Update indexed URLs'
        git push