name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - hit-it-rich
          - huuuge-casino
          - pop-slots
          - jackpot-world
          - slotomania
          - house-of-fun
          - coin-master
          - monopoly-go
          - crazy-fox
          - bingo-blitz
          - match-masters
          - willy-wonka
          - bingo-bash
          - caesars-slots
          - cash-frenzy
          - island-king
          - cashman-casino
          - piggy-go
          - doubleu-casino
          - doubledown-casino

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install jq axios cheerio

      - name: Fetch and Update Links
        run: |
          node index-js/${{ matrix.game }}.js
          echo "Content of links-json/${{ matrix.game }}.json:"
          cat links-json/${{ matrix.game }}.json
          echo "Content of _includes/${{ matrix.game }}.html:"
          cat _includes/${{ matrix.game }}.html

      - name: Generate Dynamic Post Content
        run: |
          GAME_NAME=${{ matrix.game }}
          # Fixed logic for GAME_NAME_CAPITALIZED
          GAME_NAME_CAPITALIZED=$(echo "$GAME_NAME" | sed 's/-/ /g' | sed 's/\b./\U\1/g') # Replaces dashes with spaces and capitalizes each word

          PARAGRAPH_FILE="_includes/${GAME_NAME}_post.html"

          # Template for the post content
          PARAGRAPH="Discover Daily ${GAME_NAME_CAPITALIZED} Rewards!\n\n
          Are you a fan of ${GAME_NAME_CAPITALIZED} and looking to enhance your gameplay? You've come to the right place! This page is dedicated to all ${GAME_NAME_CAPITALIZED} enthusiasts who are eager to claim free rewards every day. Here, you'll find the latest links to collect free spins, coins, chips, and other exciting bonuses to help you level up and enjoy the game even more.\n\n
          ${GAME_NAME_CAPITALIZED} is an engaging and fun game that millions love to play. Whether you're aiming to reach higher levels or just enjoy the thrill of spinning, our daily reward links will keep you in the game without breaking a sweat.\n\n
          Please note: ${GAME_NAME_CAPITALIZED} is a free-to-play app designed purely for entertainment purposes. Bonuscollector.net is an independent platform and is not affiliated with or endorsed by the creators or owners of ${GAME_NAME_CAPITALIZED}.\n\n
          Check back daily to make sure you never miss a reward!"

          echo -e "$PARAGRAPH" > "$PARAGRAPH_FILE"
          echo "Generated post content for ${GAME_NAME}:"
          cat "$PARAGRAPH_FILE"

      - name: Generate Dynamic Footer Content
        run: |
          GAME_NAME=${{ matrix.game }}
          # Fixed logic for GAME_NAME_CAPITALIZED
          GAME_NAME_CAPITALIZED=$(echo "$GAME_NAME" | sed 's/-/ /g' | sed 's/\b./\U\1/g') # Replaces dashes with spaces and capitalizes each word

          FOOTER_FILE="_includes/${GAME_NAME}_footer.html"

          # Template for the footer content
          FOOTER="### How to Claim Your ${GAME_NAME_CAPITALIZED} Rewards\n\n
          Claiming your daily rewards in ${GAME_NAME_CAPITALIZED} is quick and easy! Just follow these simple steps:\n
          1. Browse through the reward links provided above and select the ones you want to claim.\n
          2. Click on a link, and it will automatically redirect you to your ${GAME_NAME_CAPITALIZED} app or website.\n
          3. Log in with your account if prompted.\n
          4. The reward (e.g., free spins, coins, chips, or bonuses) will be added to your account instantly.\n\n
          **Tips for Claiming Rewards:**\n
          - Make sure you are logged into your ${GAME_NAME_CAPITALIZED} account before clicking the links.\n
          - Each reward link can usually be claimed only once, so check back daily for fresh links.\n
          - If a link does not work, it might have expired. Be sure to claim rewards as soon as they are posted.\n\n
          Enjoy your free rewards and have fun playing ${GAME_NAME_CAPITALIZED}!\n\n
          Please note: These rewards are provided officially by ${GAME_NAME_CAPITALIZED} and collected from publicly available sources. Bonuscollector.net is not responsible for any issues with claiming rewards."

          echo -e "$FOOTER" > "$FOOTER_FILE"
          echo "Generated footer content for ${GAME_NAME}:"
          cat "$FOOTER_FILE"

      - name: Update Include File Last Modified Date
        run: |
          export TZ=UTC
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S")
          INCLUDE_FILES_YML="_data/include_files.yml"

          if git diff --quiet _includes/${{ matrix.game }}.html; then
            echo "_includes/${{ matrix.game }}.html has not been modified. Skipping last modified date update."
          else
            if grep -q "${{ matrix.game }}.html:" "$INCLUDE_FILES_YML"; then
              sed -i "/${{ matrix.game }}.html:/,/last_modified:/s|last_modified: .*|last_modified: $TIMESTAMP|" "$INCLUDE_FILES_YML"
            else
              echo -e "\n${{ matrix.game }}.html:\n  last_modified: $TIMESTAMP" >> "$INCLUDE_FILES_YML"
            fi
            echo "Updated last modified date for _includes/${{ matrix.game }}.html"
          fi
          echo "Updated content of $INCLUDE_FILES_YML:"
          cat $INCLUDE_FILES_YML

      - name: Configure Git
        run: |
          git config --global user.email "prolladmail@gmail.com"
          git config --global user.name "Prollad99"

      - name: Commit and Push changes
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add _includes/${{ matrix.game }}.html _includes/${{ matrix.game }}_post.html _includes/${{ matrix.game }}_footer.html links-json/${{ matrix.game }}.json _data/include_files.yml
          git add package.json package-lock.json || true
          git commit -m "Update ${{ matrix.game }} reward links, content, and last modified date" || true
          git stash
          git pull --rebase || true
          git stash pop || true
          for i in {1..5}; do
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/bs-net.git && break
            echo "Retry $i: Push failed, retrying in 5 seconds..."
            sleep 5
            git pull --rebase || true
          done