name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game: [hit-it-rich, huuuge-casino, pop-slots, jackpot-world, slotomania, house-of-fun, coin-master, monopoly-go, crazy-fox, bingo-blitz, match-masters, willy-wonka, bingo-bash, caesars-slots, cash-frenzy, island-king]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install axios cheerio

      - name: Fetch and Update Links
        run: |
          node index-js/${{ matrix.game }}.js
          echo "Content of links-json/${{ matrix.game }}.json:"
          cat links-json/${{ matrix.game }}.json

      - name: Update Reward Page
        run: |
          echo '<html><body><div class="reward"><ul>' > _includes/${{ matrix.game }}.html
          jq -r '.[] | "<li><a href=\"" + .href + "\">" + .text + "</a></li>"' links-json/${{ matrix.game }}.json >> _includes/${{ matrix.game }}.html
          echo '</ul></div></body></html>' >> _includes/${{ matrix.game }}.html
          echo "Content of _includes/${{ matrix.game }}.html:"
          cat _includes/${{ matrix.game }}.html

      - name: Configure Git
        run: |
          git config --global user.email "prolladmail@gmail.com"
          git config --global user.name "Prollad99"

      - name: Check for Changes
        run: |
          git status
          git diff

      - name: Commit and Push changes with Retry
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add _includes/${{ matrix.game }}.html links-json/${{ matrix.game }}.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update ${{ matrix.game }} reward links"
            for i in {1..5}; do
              git pull --rebase && git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/bs-net.git && break || sleep 10
            done
          else
            echo "No changes to commit"
          fi