name: Update Links and Deploy

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main

jobs:
  update-links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - hit-it-rich
          - huuuge-casino
          - pop-slots
          - jackpot-world
          - slotomania
          - house-of-fun
          - coin-master
          - monopoly-go
          - crazy-fox
          - bingo-blitz
          - match-masters
          - willy-wonka
          - bingo-bash
          - caesars-slots
          - cash-frenzy
          - island-king
          - cashman-casino
          - piggy-go
          # Add more games as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install jq axios cheerio

      - name: Fetch and Update Links
        run: |
          node index-js/${{ matrix.game }}.js
          echo "Content of links-json/${{ matrix.game }}.json:"
          cat links-json/${{ matrix.game }}.json

      - name: Update Reward Page
        run: |
          echo '<html><body><div class="reward"><ul>' > _includes/${{ matrix.game }}.html
          jq -r '.[] | "<li><a href=\"" + .href + "\">" + .text + "</a></li>"' links-json/${{ matrix.game }}.json >> _includes/${{ matrix.game }}.html
          echo '</ul></div></body></html>' >> _includes/${{ matrix.game }}.html
          echo "Content of _includes/${{ matrix.game }}.html:"
          cat _includes/${{ matrix.game }}.html

      - name: Configure Git
        run: |
          git config --global user.email "prolladmail@gmail.com"
          git config --global user.name "Prollad99"

      - name: Commit and Push changes
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git add _includes/${{ matrix.game }}.html links-json/${{ matrix.game }}.json
          git add package.json package-lock.json || true
          git commit -m "Update ${{ matrix.game }} reward links" || true

          # Pull with rebase to ensure the latest changes are included
          git pull --rebase

          # Push changes, retry if necessary
          for i in {1..5}; do
            git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/bs-net.git && break
            echo "Retry $i: Push failed, retrying in 5 seconds..."
            sleep 5
            git pull --rebase
          done
